### ISSUE TITLE
TG4Event.Primaries[0].GetInteractionNumber() in spill builder

### ISSUE THREAD

**Issue by jdkio** [DUNE/2x2_sim#54]
`TG4Event.Primaries[0].GetInteractionNumber()` should be equal to the entry number in `DetSimPassThru/gRooTracker`. But that's not true for events going through `overlaySinglesIntoSpillsSorted.C`. Eg: here I'm outputing entry number vs TG4Event.Primaries[0].GetInteractionNumber()`. Since they're the same, they should point to the same index. But randomly it drops to a low number before going back to standard numbers
```
Entry 75, interaction number of vtx 0: 72
Entry 76, interaction number of vtx 0: 73
Entry 77, interaction number of vtx 0: 74
Entry 78, interaction number of vtx 0: 1
Entry 79, interaction number of vtx 0: 75
Entry 80, interaction number of vtx 0: 76
Entry 81, interaction number of vtx 0: 77
```
I assume that's because the numbers are pulled from their respective streams. So every time it drops, it's because it's switching from pulling from the more common rock interactions to a fiducial interaction. This is bad because the index no longer points to the correct position. And also because there are multiple vertices that point to the same index. The fix is to adjust the numbers while saving in `overlaySinglesIntoSpillsSorted`. These numbers are used to map to the primary vertex that created particles in the TMS, and can be useful like that for others if this mapping is preserved correctly.

Edit: A similar thing is true for event.Eventid:
```
Entry 647, interaction number of vtx 0: 633, vs event.EventId 634
Entry 648, interaction number of vtx 0: 12, vs event.EventId 13
```

**Comment by mjkramer** [comment]
In the output from the spill builder, the `EDepSimEvents` and `DetSimPassThru/gRooTracker` trees are aligned with each other. So it would be easy enough, in future productions, to set the `InteractionNumber` of the `i`th `EDepSimEvent` to be (drumroll...) `i`, if that makes the TMS code happier. I'll make that change.

For processing existing MC, I guess you'd need to apply a temporary hack that uses `i` (i.e. the entry number) instead of the current value of `InteractionNumber`.

FWIW, the 2x2+MINERvA workflow doesn't use `InteractionNumber` at all, so that would explain why nobody raised this issue in the past. You're right, though; the `InteractionNumber` initially assigned by `edep-sim`, is ambiguous and effectively useless after going through the spill-building pipeline.

The disagreement between entry number and `EventId` is unavoidable since we're mixing fiducial and rock events, and the `EventId` is (intentionally) not rewritten. In fact, since each spill-built file is made from 10+10 (fiducial+rock) files, the same `EventId` can be repeated up to 20 times. The `RunId` (where "small" numbers are fiducial input files and "large" numbers are rock inputs) breaks the degeneracy.

**Comment by mjkramer** [comment]
With the above commit, `InteractionNumber` is now getting reassigned properly:

```
root [1] EDepSimEvents->Scan("InteractionNumber")
***********************************
*    Row   * Instance * Interacti *
***********************************
*        0 *        0 *         0 *
*        1 *        0 *         1 *
*        2 *        0 *         2 *
*        3 *        0 *         3 *
*        4 *        0 *         4 *
*        5 *        0 *         5 *
*        6 *        0 *         6 *
*        7 *        0 *         7 *
*        8 *        0 *         8 *
```

@jdkio Feel free to reopen this issue if this fix doesn't fully address it.
